version: '2.1'
# zalenium dashboard - http://localhost:4444/dashboard/
# zalenium live preview - http://localhost:4444/grid/admin/live
services:

  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "Asia/Kolkata"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled true
            --testingBotEnabled false
            --cbtEnabled false
            --startTunnel true
    environment:
      - PULL_SELENIUM_IMAGE=true
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER=abhilash99
      - BROWSER_STACK_KEY=jVTny2MpChQdEJRrxoyR
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - CBT_USERNAME
      - CBT_AUTHKEY